name: Windows build

on:
  push:
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: Install GStreamer
        run: |
          choco install -y --no-progress gstreamer --version=1.24.2
          choco install -y --no-progress gstreamer-devel --version=1.24.2
          $root = $env:SYSTEMDRIVE + '\gstreamer\1.0\msvc_x86_64\'
          # Github runners work on both C or D drive
          if (-not (Test-Path -Path $root -PathType Container)) { $root = 'D:\gstreamer\1.0\msvc_x86_64\' }
          dir $root
          Add-Content -Path $env:GITHUB_ENV -Value "GSTREAMER_1_0_ROOT_MSVC_X86_64=$root"
          Add-Content -Path $env:GITHUB_PATH -Value "$root\bin"
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.72.0"
      - uses: Swatinem/rust-cache@v2
      - name: Build
        shell: bash
        run: cargo build --release
      - uses: actions/upload-artifact@v4
        with:
          name: neolink-windows
          path: target/release/neolink.exe
